server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres-payment-db:5432/payment_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
